/**
 * Access Code Store
 *
 * Manages access gating for ebook purchasers.
 * Validates access codes against the Supabase `access_codes` table.
 * Codes are generated by the sales site via generate_access_codes() RPC.
 */

import { create } from 'zustand'
import { persist } from 'zustand/middleware'
import { supabase } from '@/lib/supabase'

interface AccessState {
  // Whether user has validated access
  hasAccess: boolean
  // The access code that was used
  licenseKey: string | null
  // When access was granted
  accessGrantedAt: string | null
  // Customer email from access_codes table
  email: string | null
  // Instance ID for this device
  instanceId: string | null

  // Actions
  validateCode: (code: string) => Promise<{ success: boolean; error?: string }>
  revokeAccess: () => void
  checkAccess: () => boolean
}

export const useAccessStore = create<AccessState>()(
  persist(
    (set, get) => ({
      hasAccess: false,
      licenseKey: null,
      accessGrantedAt: null,
      email: null,
      instanceId: null,

      validateCode: async (code: string) => {
        // Access codes are 8-char uppercase alphanumeric
        const trimmedCode = code.trim().toUpperCase()

        if (trimmedCode.length < 8) {
          return { success: false, error: 'Invalid access code format' }
        }

        // Check for master code (set via environment variable)
        const masterCode = import.meta.env.VITE_MASTER_ACCESS_CODE
        if (masterCode && trimmedCode === masterCode.toUpperCase()) {
          if (import.meta.env.DEV) console.log('[Access] Master code used')
          set({
            hasAccess: true,
            licenseKey: 'MASTER',
            accessGrantedAt: new Date().toISOString(),
            email: null,
            instanceId: 'master-access'
          })
          return { success: true }
        }

        // Validate against Supabase access_codes table
        if (!supabase) {
          if (import.meta.env.DEV) {
            // DEV only: accept any 8+ char code when Supabase not configured
            console.log('[Access] Supabase not configured, using dev fallback')
            set({
              hasAccess: true,
              licenseKey: trimmedCode,
              accessGrantedAt: new Date().toISOString(),
              email: null,
              instanceId: 'dev-instance'
            })
            return { success: true }
          }
          return { success: false, error: 'Validation unavailable. Please try again later.' }
        }

        try {
          const { data, error } = await supabase
            .from('access_codes' as any)
            .select('code, email, is_active')
            .eq('code', trimmedCode)
            .single()

          if (error || !data) {
            return { success: false, error: 'Invalid access code' }
          }

          if (!(data as any).is_active) {
            return { success: false, error: 'This access code has been deactivated.' }
          }

          // Valid code — grant access
          set({
            hasAccess: true,
            licenseKey: trimmedCode,
            accessGrantedAt: new Date().toISOString(),
            email: (data as any).email || null,
            instanceId: null
          })

          // Try to mark the code as used (fire-and-forget, may fail due to RLS)
          try {
            await supabase
              .from('access_codes' as any)
              .update({ used_at: new Date().toISOString() } as any)
              .eq('code', trimmedCode)
          } catch {
            // Expected to fail if RLS blocks updates — that's fine
          }

          return { success: true }
        } catch (err) {
          console.error('Access code validation error:', err)

          // Network error — allow offline access if same code was previously validated
          const currentState = get()
          if (currentState.hasAccess &&
              currentState.licenseKey === trimmedCode &&
              currentState.accessGrantedAt) {
            const accessDate = new Date(currentState.accessGrantedAt)
            const thirtyDaysAgo = new Date()
            thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30)

            if (accessDate > thirtyDaysAgo) {
              return { success: true }
            }
            return {
              success: false,
              error: 'Access code needs to be revalidated. Please check your internet connection.'
            }
          }

          return {
            success: false,
            error: 'Unable to validate code. Please check your internet connection.'
          }
        }
      },

      revokeAccess: () => {
        set({
          hasAccess: false,
          licenseKey: null,
          accessGrantedAt: null,
          email: null,
          instanceId: null
        })
      },

      checkAccess: () => {
        return get().hasAccess
      }
    }),
    {
      name: 'gamify-gains-access',
      version: 2
    }
  )
)
